name: Create and Publish Release
on:
  push:
    branches:
      - main
      - '*[0-9].*[0-9].x'
      - '*[0-9].x.x'
      - dev
      - alpha
      - beta

jobs:
  semantic-release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      last_release_git_tag: ${{ steps.semantic.outputs.last_release_git_tag }}
      last_release_version: ${{ steps.semantic.outputs.last_release_version }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/set-up-node
    - run: npm ci
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@ba330626c4750c19d8299de843f05c7aa5574f62 # v5.0.2
      id: semantic # Need an `id` for output variables
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          @semantic-release/changelog@6.0.2
          @semantic-release/git@10.0.1
          conventional-changelog-conventionalcommits@5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
        GH_USERNAME: lime-opensource
        GH_TOKEN: ${{ secrets.CREATE_RELEASE }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
